Entity/BackendUser.php
<?php

namespace Innomedio\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * User
 *
 * @ORM\Table(name="backend_user")
 * @ORM\Entity(repositoryClass="Innomedio\UserBundle\Repository\BackendUserRepository")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="innomedio.user.email_taken"
 * )
 */
class BackendUser implements UserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var BackendUserGroup
     *
     * @ORM\ManyToOne(targetEntity="BackendUserGroup", inversedBy="users")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $group;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=60, unique=true)
     * @Assert\Email(
     *     message = "innomedio.user.invalid_email"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLogin;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param mixed $username
     */
    public function setUsername($username)
    {
        $this->username = $username;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getLastLogin()
    {
        return $this->lastLogin;
    }

    /**
     * @param mixed $lastLogin
     */
    public function setLastLogin($lastLogin)
    {
        $this->lastLogin = $lastLogin;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }

    /**
     * @return null
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * @return array
     */
    public function getRoles()
    {
        $return = array('ROLE_BACKEND');

        if ($this->group && $this->group->isRoot()) {
            $return[] = 'ROLE_ROOT';
        }

        if ($this->getGroup()) {
            foreach ($this->getGroup()->getRights() as $right) {
                $return[] = $right->getName();
            }
        }

        return $return;
    }

    /**
     *
     */
    public function eraseCredentials()
    {

    }

    /**
     * @return string
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password
        ));
    }

    /**
     * @param string $serialized
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password
            ) = unserialize($serialized);
    }

    /**
     * @return BackendUserGroup
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * @param BackendUserGroup $group
     */
    public function setGroup(BackendUserGroup $group)
    {
        $this->group = $group;
    }
}


Controller/Backend/AccessController.php
<?php

namespace Innomedio\UserBundle\Controller\Backend;

use Innomedio\BackendThemeBundle\Controller\BackendThemeController;
use Innomedio\BackendThemeBundle\Service\Theme\ThemeManager;
use Symfony\Component\Routing\Annotation\Route;

class AccessController extends BackendThemeController
{
    /**
     * @Route("/access", name="innomedio.user.access")
     */
    public function index()
    {
        $this->header()->addBreadcrumb('innomedio.user.access');

        return $this->render('@InnomedioBackendTheme/item_page.html.twig', array(
            'type' => 'access'
        ));
    }
}

Controller/Backend/BackendUserController.php
<?php
namespace Innomedio\UserBundle\Controller\Backend;

use Innomedio\BackendThemeBundle\Controller\BackendThemeController;
use Innomedio\BackendThemeBundle\Service\Ajax\AjaxResponse;
use Innomedio\UserBundle\Entity\BackendUser;
use Innomedio\UserBundle\Form\BackendUserType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Security("has_role('ROLE_BACKEND_USERS')")
 * @Route("/access/users")
 */
class BackendUserController extends BackendThemeController
{
    /**
     * @Route("/", name="innomedio.user.users.list")
     * @return Response
     */
    public function list()
    {
        $this->header()->addBreadcrumb('innomedio.user.access', $this->generateUrl('innomedio.user.access'));
        $this->header()->addBreadcrumb('innomedio.user.users');

        return $this->render('@InnomedioUser/backend/users/list.html.twig', array(
            'users' => $this->getDoctrine()->getRepository('InnomedioUserBundle:BackendUser')->findAll()
        ));
    }

    /**
     * @Route(
     *     "/{action}/{id}",
     *     name="innomedio.user.users.form",
     *     requirements={
     *         "action" = "add|edit",
     *         "id" = "\d+"
     *     },
     *     defaults={"id" = 0}
     * )
     *
     * @param $action
     * @param BackendUser|null $user
     * @return Response
     */
    public function form($action, BackendUser $user = null)
    {
        if (!$user) {
            $user = new BackendUser();
        }

        $this->header()->addBreadcrumb('innomedio.user.access', $this->generateUrl('innomedio.user.access'));
        $this->header()->addBreadcrumb('innomedio.user.users', $this->generateUrl('innomedio.user.users.list'));
        $this->header()->addBreadcrumb('innomedio.user.users.title.' . $action);

        $form = $this->createForm(BackendUserType::class, $user);
        $form->add('submit', SubmitType::class, array(
            'label' => 'innomedio.backend_theme.global.' . $action
        ));

        return $this->render('@InnomedioUser/backend/users/form.html.twig', array(
            'form' => $form->createView(),
            'activeNav' => 'access',
            'activeSubnav' => 'backend_users'
        ));
    }

    /**
     * @Route(
     *     "/submit/{id}",
     *     name="innomedio.user.users.submit"),
     *     requirements={
     *         "id" = "\d+"
     *     },
     *     defaults={"id" = 0}
     *
     * @param $id
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function submit($id, Request $request)
    {
        $response = new AjaxResponse();

        if ($id > 0) {
            $user = $this->getDoctrine()->getRepository('InnomedioUserBundle:BackendUser')->find($id);
            $action = 'edit';
        } else {
            $user = new BackendUser();
            $action = 'add';
        }

        $activePassword = $user->getPassword();

        $form = $this->createForm(BackendUserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setUsername($user->getEmail());

            if (!empty($form->get('password')->getData())) {
                $encodedPassword = $this->get('security.password_encoder')->encodePassword($user, $user->getPassword());
                $user->setPassword($encodedPassword);
            } else {
                $user->setPassword($activePassword);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $response->setSuccess(true);
            $response->setRedirect($this->generateUrl('innomedio.user.users.list'));
            $response->setMessage($this->get('translator')->trans('innomedio.user.users.submit.success.' . $action));
        } else {
            $response->setErrors($this->get('innomedio.backend_theme.error_parser')->getErrors($form, $user));
        }

        return new JsonResponse($response->getResponse());
    }

    /**
     * @Route("/remove/{id}", requirements={"id" = "\d+"}, name="innomedio.user.users.remove")
     * @param BackendUser $user
     * @return JsonResponse
     */
    public function ajaxRemove(BackendUser $user)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($user);
        $em->flush();

        return new JsonResponse(array(
            'success' => true
        ));
    }
}

Controller/Backend/BackendUserGroupController.php
<?php
namespace Innomedio\UserBundle\Controller\Backend;

use Innomedio\BackendThemeBundle\Controller\BackendThemeController;
use Innomedio\BackendThemeBundle\Service\Ajax\AjaxResponse;
use Innomedio\UserBundle\Entity\BackendUserGroup;
use Innomedio\UserBundle\Form\BackendUserGroupType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Security("has_role('ROLE_BACKEND_GROUPS')")
 * @Route("/access/groups")
 */
class BackendUserGroupController extends BackendThemeController
{
    /**
     * @Route("/", name="innomedio.user.groups.list")
     * @return Response
     */
    public function list()
    {
        $this->header()->addBreadcrumb('innomedio.user.access', $this->generateUrl('innomedio.user.access'));
        $this->header()->addBreadcrumb('innomedio.user.user_groups');

        return $this->render('@InnomedioUser/backend/groups/list.html.twig', array(
            'groups' => $this->getDoctrine()->getRepository('InnomedioUserBundle:BackendUserGroup')->findAll()
        ));
    }

    /**
     * @Route(
     *     "/{action}/{id}",
     *     name="innomedio.user.groups.form",
     *     requirements={
     *         "action" = "add|edit",
     *         "id" = "\d+"
     *     },
     *     defaults={"id" = 0}
     * )
     *
     * @param $action
     * @param BackendUserGroup|null $group
     * @return Response
     */
    public function form($action, BackendUserGroup $group = null)
    {
        $this->header()->addBreadcrumb('innomedio.user.access', $this->generateUrl('innomedio.user.access'));
        $this->header()->addBreadcrumb('innomedio.user.user_groups', $this->generateUrl('innomedio.user.groups.list'));
        $this->header()->addBreadcrumb('innomedio.user.group.title.' . $action);

        $form = $this->createForm(BackendUserGroupType::class, $group);
        $form->add('submit', SubmitType::class, array(
            'label' => 'innomedio.backend_theme.global.' . $action
        ));

        return $this->render('@InnomedioUser/backend/groups/form.html.twig', array(
            'form' => $form->createView(),
            'activeNav' => 'access',
            'activeSubnav' => 'backend_groups'
        ));
    }

    /**
     * @Route(
     *     "/submit/{id}",
     *     name="innomedio.user.groups.submit"),
     *     requirements={
     *         "id" = "\d+"
     *     },
     *     defaults={"id" = 0}
     *
     * @param $id
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function submit($id, Request $request)
    {
        $response = new AjaxResponse();

        if ($id > 0) {
            $group = $this->getDoctrine()->getRepository('InnomedioUserBundle:BackendUserGroup')->find($id);
            $action = 'edit';
        } else {
            $group = new BackendUserGroup();
            $action = 'add';
        }

        $form = $this->createForm(BackendUserGroupType::class, $group);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($group);
            $em->flush();

            $response->setSuccess(true);
            $response->setRedirect($this->generateUrl('innomedio.user.groups.list'));
            $response->setMessage($this->get('translator')->trans('innomedio.user.groups.submit.success.' . $action));
        } else {
            $response->setErrors($this->get('innomedio.backend_theme.error_parser')->getErrors($form, $group));
        }

        return new JsonResponse($response->getResponse());
    }

    /**
     * @Route("/remove/{id}", requirements={"id" = "\d+"}, name="innomedio.user.groups.remove")
     * @param BackendUserGroup $group
     * @return JsonResponse
     */
    public function ajaxRemove(BackendUserGroup $group)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($group);
        $em->flush();

        return new JsonResponse(array(
            'success' => true
        ));
    }
}

Controller/Backend/SecurityController.php
<?php
namespace Innomedio\UserBundle\Controller\Backend;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SecurityController extends Controller
{
    /**
     * @Route("/login", name="innomedio.user.login")
     * @return Response
     */
    public function index()
    {
        if ($this->getUser()) {
            return $this->redirectToRoute("innomedio.backend_theme.dashboard");
        }

        $error = $this->get('security.authentication_utils')->getLastAuthenticationError();
        $lastUsername = $this->get('security.authentication_utils')->getLastUsername();

        return $this->render('@InnomedioBackendTheme/security/login.html.twig', array(
            'error' => $error,
            'lastUsername' => $lastUsername,
            'loginAction' => $this->generateUrl('innomedio.user.login_submit'),
            'loginRedirect' => $this->generateUrl('innomedio.backend_theme.dashboard'),
            'loginError' => $error
        ));
    }

    /**
     * @Route("/login/submit", name="innomedio.user.login_submit")
     *
     * @param Request $request
     */
    public function loginAction(Request $request)
    {

    }

    /**
     * @Route("/logout", name="innomedio.user.logout")
     * @param Request $request
     */
    public function logoutAction(Request $request)
    {

    }

    /**
     * @Route("/", name="innomedio.user.anonymous_redirect");
     * @return RedirectResponse
     */
    public function cmsRedirect()
    {
        if ($this->getUser()) {
            return $this->redirectToRoute("innomedio.backend_theme.dashboard");
        }

        return $this->redirectToRoute('innomedio.user.login');
    }
}

Resources/views/backend/users/form.html.twig
{% extends '@InnomedioBackendTheme/backend_base.html.twig' %}

{% block content %}
    <div class="main-content mb-60">
        {% form_theme form '@InnomedioBackendTheme/form/template-fields.html.twig' %}

        {{ form_start(form, {'action': url('innomedio.user.users.submit', {id: app.request.get('id')}), 'attr': {'class': 'ajax-form'}}) }}
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            {{ form_label(form.firstName) }}
                            {{ form_widget(form.firstName) }}
                        </div>

                        <div class="form-group col-md-6">
                            {{ form_label(form.lastName) }}
                            {{ form_widget(form.lastName) }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-4">
                            {{ form_label(form.email) }}
                            {{ form_widget(form.email) }}
                        </div>

                        <div class="form-group col-md-4">
                            {{ form_label(form.group) }}
                            {{ form_widget(form.group) }}
                        </div>

                        <div class="form-group col-md-4">
                            {{ form_label(form.password) }}
                            {{ form_widget(form.password) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

Resources/views/backend/users/list.html.twig
{% extends "@InnomedioBackendTheme/backend_base.html.twig" %}

{% block content %}
    <div class="main-content mb-60">
        {% if users %}
            <div class="card">
                <div class="card-body p-0">
                    <table class="table mb-0">
                        <thead>
                        <tr>
                            <th>{{ 'innomedio.backend_theme.global.email'|trans }}</th>
                            <th>{{ 'innomedio.backend_theme.global.name'|trans }}</th>
                            <th>{{ 'innomedio.user.users.group'|trans }}</th>
                            <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        {# @var user \Innomedio\UserBundle\Entity\BackendUser #}
                        {% for user in users %}
                            {% if 'ROLE_ROOT' not in user.roles or is_granted('ROLE_ROOT') %}
                                <tr class="item-to-remove">
                                    <td>{{ user.email }}</td>
                                    <td>{{ user.firstName }} {{ user.lastName }}</td>
                                    <td>
                                        {% if (user.group) %}
                                            <a href="{{ url('innomedio.user.groups.form', {id: user.group.id, action: 'edit'}) }}">{{ user.group.name }}</a>
                                        {% endif %}
                                    </td>

                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="text-lighter" href="#" data-toggle="dropdown" aria-expanded="false"><i class="ti-more-alt rotate-90"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end">
                                                <a class="dropdown-item" href="{{ url('innomedio.user.users.form', {action: 'edit', id: user.id}) }}"><i class="fa fa-fw fa-search"></i> {{ 'innomedio.backend_theme.global.edit'|trans }}</a>

                                                {% if app.user.id != user.id %}
                                                <div class="dropdown-divider"></div>
                                                <a class="ajax-remove dropdown-item"
                                                   href="{{ url('innomedio.user.users.remove', {id: user.id}) }}"
                                                ><i class="fa fa-fw fa-trash"></i> {{ 'innomedio.backend_theme.global.remove'|trans }}</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    </div>

    <div class="fab fab-fixed">
        <a class="btn btn-float btn-primary"
           href="{{ url('innomedio.user.users.form', {action: 'add'}) }}"
           data-provide="tooltip"
           data-original-title="{{ 'innomedio.backend_theme.global.add'|trans }}"
        ><i class="ti-plus"></i></a>
    </div>
{% endblock %}